### ISSUE TITLE
Future development

### ISSUE THREAD

**Issue by Klauzi19** [OttoMeister/Siemens-Tia-Portal-PID-Controller#1]
Hello

I am very happy with your PID Regulator, it works without any problems. Are they planning further development for the future or has the project died?

Friendly greetings

**Comment by sk8net** [comment]
> Hello
> 
> I am very happy with your PID Regulator, it works without any problems. Are they planning further development for the future or has the project died?
> 
> Friendly greetings

**Comment by OttoMeister** [comment]
Hi Klauzi19 and sk8net, 

please explain how you use this software and how you can contribute.

Open works

    Writing instructions
    Create sample projects
    Convert everything to English
    debugging
    Porting to different controllers

**Comment by Klauzi19** [comment]
@OttoMeister 

Jetzt mal in Deutsch :). Ich bin von der Logo zu der S7-1200 umgestiegen. Vorteil bei der Logo war der sehr einfache PI-Regler. Ich verwende den PID Regler für Druckregelung (Lüfter, Verdichter). Zukünftig eventuell auch für simple Lüftungsregelungen. Ich denke für diese 'einfachen' Regelungen reicht der Regler von Otto Meister absolut. Der Siemens Regler ist Super aber einfach zu gross geraten....
Wie ich helfen könnte:
- Debugging
- Anleitung schreiben

@OttoMeister 

Now in English :). I switched from the logo to the S7-1200. The advantage of the logo was the very simple PI controller. I use the PID controller for pressure control (fan, compressor). In the future, for simple ventilation regulations. I think Otto Meister's regulator is enough for these ' simple ' regulations. The Siemens controller is super but just too big ...
How I could help:
-Debugging
-Write instructions

**Comment by OttoMeister** [comment]
Ich hab mal den Regler geupdatet. Der PI Teil hat einen besseren Anti-Windup. Bei meinen Hochdruckpumpen kann das Vollaufen des Integrals böse Folgen haben. Dehalb immer den Reset-Eingang benutzen wenn die Regelstrecke gestört ist. Hier durch wird der Integrall auf Null gesetzt.
Ich habe der D Regler bisher noch nicht benutzt. PI reicht zur Druckreglung bei mir vollkommen. Ein Schwingen der Reglung hätte fatale Folgen. Eine Temperaturreglung habe ich auch noch nicht gemacht. Hoffe das kommt bald.
Zur Entwicklung des ganzen PID Reglers habe ich ein Projekt mit simulierter Regelstrecke. Dort kann ich die Regelantwort vom Siemens-Regler mit meinem Regler vergleichen. Das Projekt läuft nicht im Simulator wegen dem Siemens-Regler. Ohne diesen gehts. Ihr braucht ne 1214 CPU mit TIA 15.0.

**Comment by Klauzi19** [comment]
- Habe die Änderung bei mir integriert. Teste es sobald der nächste Rückkühler kommt. 
- TIA V15 möchte dein Projekt nicht öffnen, es fehlen einige Produkte (G110M, G120, etc...)
- D-Anteil habe ich mal probiert, aber mir ist keine grosse Wirkung aufgefallen
- Was mir noch fehlt in ein BOOL für die Wirkungsumkehr, anstelle -Werte eintragen

**Comment by OttoMeister** [comment]
- Nimm erst mal nur den PI Regler. Dank der linear ansteigenden Integralregelung ist er extrem gutmütig. Der Diferenzial ist dagegen Logarithmisch und neigt zum Überschwingen.
- Im Anhang neu ohne Smartdrive abhängigkeit.
- Wie gesagt der D funktioniert, aber ich fand ihn schwer zum Einstellen.
- Der Regler bringt 0 bis 100 als Ausgang. Einfach 100 minus Reglerausgang machen. Würde ich so händisch machen, sonst ist der Regler schnell überfrachtet mit Otionen. Schau dir mal die OSCAT Vorlage an. Die haben einenn ganzen Zoo von Zusatzroutinen um den einfachen Regler gebastelt.

[PID-Regler.zip](https://github.com/OttoMeister/Siemens-Tia-Portal-PID-Controller/files/3141820/PID-Regler.zip)

**Comment by Klauzi19** [comment]
- Den Bool für die Wirkrichtung bau ich mir doch noch ein, ist die einzige Option die ich brauche.  Bei meinen Anwendungen ist es möglich dass ich beide Richtungen brauche (Rückkühler im Sommer, Rückerwärmer im Winter)….
- D werde ich bei der nächsten realen Anlage erneut mal testen, hatte wohl zu wenig Geduld.... Was bedeute genau die Haltezeit?
- Simulation der Regelung funktioniert ohne Probleme.....

**Comment by OttoMeister** [comment]
- Kein Problem, gerade deshalb habe ich ja sowas gemacht. Den Siemensregler von TIA ist leider nicht einsehbar oder änderbar. Den PID code von Simatic-Manager Step7 habe ich hier auf Github schon gesehen.
- Der  **ir_DifferenzialVerstärkung**  ist die Reglerantwort in der Amplitude und **itime_HaltezeitDifferezial**  ist die Reglerantwort auf die Zeit. Das schaust du dir mal am besten am Simulator an.
- Mein PID Regler läuft auf dem Simulator. Der Siemens nicht. Achtung mit der Simulation, es wird eine Heizung simuliert. Eine Druckreglung verhält sich anders. Bitte nachschauen in der **Library for Controlled
System Simulation with STEP 7 (TIA Portal)** [closed-loop-control-of-simulated-controlled-systems-in-the-s7-1500-with-pid_compact-v2](https://support.industry.siemens.com/cs/document/79047707/closed-loop-control-of-simulated-controlled-systems-in-the-s7-1500-with-pid_compact-v2?dti=0&lc=en-PL)
